export LANG=ja_JP.UTF-8
export LANGUAGE=ja_JP.UTF-8
export LC_ALL=ja_JP.UTF-8
export EDITOR=vim
export JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF-8
export HOMEBREW_CASK_OPTS="--appdir=/Applications"
export WORDCHARS="?!"
export LS_COLORS='di=34:ln=35:so=32:pi=33:ex=33:bd=46;34:cd=43;34:su=41;30:sg=46;30:tw=42;30:ow=43;30'
export LSCOLORS=exfxcxdxdxegedabagacad
export ZLS_COLORS=$LS_COLORS
export HISTFILE=$HOME/.zsh-history
export HISTSIZE=10000
export SAVEHIST=100000
export ANDROID_SDK_ROOT=~/Library/Android/sdk
export NODE_OPTIONS="--max-old-space-size=8192"
export XDG_CONFIG_HOME="$HOME/.config"
export GIT_TEMPLATE_DIR="$XDG_CONFIG_HOME/git/.git-template"
# export VOLTA_HOME="$HOME/.volta"
export BUN_INSTALL="$HOME/.bun"
