export PATH="/usr/local/bin:$PATH"
export PATH="/opt/homebrew/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"
export PATH="$PATH:`yarn global bin`"
export PATH="$HOME/go/bin:$PATH"
export PATH="$ANDROID_HOME/tools/bin:$PATH"
export PATH="$HOME/.cargo/bin:$PATH"
export PATH="$VOLTA_HOME/bin:$PATH"
