#!/usr/bin/env ruby

black_words = [
  'binding.pry',
]

found_words = []
changed_files = `git diff --cached --name-only HEAD`
changed_files.each_line do |filename|
  changes = `git diff --cached -U0 HEAD -- "#{filename.chomp}"`
  black_words.each do |word|
    result = changes.split(/\n/).grep(/^\+.*\b#{word}\b/)
    unless result.empty?
      found_words << word
    end
  end
end

unless found_words.empty?
  found_words.each { |word| puts "WARNING: '#{word}' is found." }
  puts "Please add `--no-verify` option if you want to commit with no change."
  exit 1
end

unless system("git config --local user.email")
  puts "Please run `git config --local user.email <YOUR_EMAIL_ADDRESS>`"
  exit 1
end
