export LANG=ja_JP.UTF-8
export LANGUAGE=ja_JP.UTF-8
export LC_ALL=ja_JP.UTF-8
export EDITOR=vim
export JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF-8
export HOMEBREW_CASK_OPTS="--appdir=/Applications"
export WORDCHARS="?!"
export LS_COLORS='di=34:ln=35:so=32:pi=33:ex=33:bd=46;34:cd=43;34:su=41;30:sg=46;30:tw=42;30:ow=43;30'
export LSCOLORS=exfxcxdxdxegedabagacad
export ZLS_COLORS=$LS_COLORS
export HISTFILE=$HOME/.zsh-history
export HISTSIZE=10000
export SAVEHIST=100000
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
export ANDROID_HOME="$HOME/Library/Android/sdk"
export PATH="$ANDROID_HOME/tools/bin:$PATH"
